# -*- coding: utf-8 -*-
"""automate_Ahmad_Riki_Andreas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJPMY868bvafYsVmG728h6Md5zaBNWrS
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd


def load_data():
    iris = load_iris()

    df = pd.DataFrame(
        iris.data,
        columns=iris.feature_names
    )

    df['target'] = iris.target

    return df


def preprocessing():
    df = load_data()

    X = df.drop('target', axis=1)
    y = df['target']

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    return X_train, X_test, y_train, y_test


if __name__ == "__main__":
    X_train, X_test, y_train, y_test = preprocessing()

    print("Preprocessing berhasil")
    print("Shape X_train:", X_train.shape)
    print("Shape X_test:", X_test.shape)